version: "3.7"
services:
  db:
    image: mysql:8.0.33
    volumes:
      - ./mydb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: "%" # Allow connections from any host
      MYSQL_ROOT_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  devops-rest:
    depends_on:
      - db
    image: toby4all/tobby_pipeline:${IMAGE_TAG}
    ports:
      - "5000:5000"
    environment:
      MYSQL_DB_HOST: db # Use the service name as the hostname
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: mysql
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://db:3306"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mydb:
