apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
      - name: python-flask
        image: "{{ .Values.rest_app.image.repository }}:{{ .Values.image.tag }}"  # Specify the image here
        imagePullPolicy: {{ .Values.rest_app.image.pullPolicy }}
        ports:
        - containerPort: 5000
