apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mysql  # Update the label to match the app label in the template
  template:
    metadata:
      labels:
        app: mysql  # Update the label to match the selector
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        imagePullPolicy: {{ .Values.mysql.imagePullPolicy }}
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.rootPassword }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.databaseName }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.mysqlUser }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql.mysqlPassword }}

