apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - protocol: "TCP"
    port: 3306  # Adjust the port as needed for MySQL
    targetPort: 3306  # Adjust the targetPort as needed
  type: ClusterIP  # Match the service type to the value in values.yaml
