apiVersion: v1
kind: Service
metadata:
  name: python-flask-service
spec:
  selector:
    app: python-flask
  ports:
  - protocol: "TCP"
    port: 30001  # Use the same NodePort specified in values.yaml
    targetPort: 5000
  type: {{ .Values.service.rest_app.type }}
