# Values for the rest_app deployment
rest_app:
  image:
    repository: toby4all/tobby_pipeline
    pullPolicy: Always
    tag: ""

# Values for the MySQL 8.0.33 database deployment
mysql:
  image:
    repository: mysql
    tag: "8.0.33"
  rootPassword: mysql
  databaseName: mydb
  mysqlUser: user
  mysqlPassword: password

# Service configuration for the rest_app
service:
  rest_app:
    name: rest-app-service
    type: LoadBalancer

# Service configuration for MySQL
service:
  mysql:
    name: mysql-service
    type: ClusterIP  # Choose the appropriate service type for MySQL

# Common configuration
replicaCount: 5




