# Values for the rest_app deployment
rest_app:
  image:
    repository: toby4all/tobby_pipeline
    pullPolicy: Always  # Set to "Always" for the rest-app

# Values for the MySQL 8.0.33 database deployment
mysql:
  image:
    repository: mysql
    tag: "8.0.33"
  rootPassword: mysql
  databaseName: mydb
  mysqlUser: user
  mysqlPassword: password
  imagePullPolicy: Always  # To pull the latest image from the repository

# Service configuration for the rest_app and MySQL
service:
  rest_app:
    name: rest-app-service
    type: NodePort
    nodePort: 30001

  mysql:
    name: mysql-service
    type: ClusterIP  # Choose the appropriate service type for MySQL

# Common configuration
replicaCount: 5





